name: build
on:
  schedule:
  # github 延迟测试，UTC 时间测试 https://zhuanlan.zhihu.com/p/369780435
    - cron: "0 */6 * * *"
  workflow_dispatch: ~
jobs:
  sync:
    name: Sync from notion
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Clean the old post
        run: |
          rm -rf ./content/*
      - name: notion-site
        uses: pkwenda/notion-site@master
        env:
          NOTION_SECRET : ${{ secrets.NOTION_SECRET }}
      - name: Commit files
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "New results"
          git config pull.rebase false
          git pull
          git push 
      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./content/**/*.md
          commit_message: 'notion-site: update articles (auto)'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public