name: build
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch: ~
jobs:
  sync:
    name: Sync from notion
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Clean the old post
        run: |
          rm -rf ./content/*
      - name: notion-site
        uses: pkwenda/notion-site@master
        env:
          NOTION_SECRET : ${{ secrets.NOTION_SECRET }}
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "New results"
          git config pull.rebase false
          git pull
          git push 
      - name: Setup Hugo
        if: steps.verify_diff.outputs.changed == 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - uses: actions/cache@v2
        if: steps.verify_diff.outputs.changed == 'true'
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build
        if: steps.verify_diff.outputs.changed == 'true'
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public